name: PowerShell CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        shell: [pwsh]
        include:
          - os: windows-latest
            shell: powershell
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v4

      - name: List repo (debug)
        run: |
          ls -R
        shell: bash

      - name: Show script (debug)
        run: |
          echo "===== Build-MarksTemple.ps1 ====="
          cat ./src/Build-MarksTemple.ps1
          echo "===== Test file ====="
          cat ./tests/Build-MarksTemple.Tests.ps1
        shell: bash

      - name: Install Pester
        run: |
          Install-Module Pester -Force -Scope CurrentUser
          Get-Module Pester -ListAvailable | Select-Object Name,Version | Sort-Object Version -Descending | Select-Object -First 1
        shell: ${{ matrix.shell }}

      - name: Run Pester
        run: |
          Write-Host "Pester version:"; (Get-Module Pester -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1).Version
          Invoke-Pester -Path ./tests -Output Detailed -Verbose
        shell: ${{ matrix.shell }}