name: PowerShell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows-powershell:
    name: Windows PowerShell (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        run: Install-Module -Name Pester -Force -Scope CurrentUser
        shell: powershell
      - name: Run Pester tests
        run: |
          Import-Module Pester
          Invoke-Pester -Path tests -Output Detailed
        shell: powershell

  test-windows-pwsh:
    name: PowerShell Core (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        run: Install-Module -Name Pester -Force -Scope CurrentUser
        shell: pwsh
      - name: Run Pester tests
        run: |
          Import-Module Pester
          Invoke-Pester -Path tests -Output Detailed
        shell: pwsh

  test-linux-pwsh:
    name: PowerShell Core (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pester
        run: pwsh -c "Install-Module -Name Pester -Force -Scope CurrentUser"
      - name: Run Pester tests
        run: pwsh -c "Import-Module Pester; Invoke-Pester -Path tests -Output Detailed"