name: PowerShell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows-powershell:
    name: Windows PowerShell (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repo files
        run: ls -R
        shell: bash
      - name: Show test file contents
        run: cat ./tests/Build-MarksTemple.Tests.ps1
        shell: bash
      - name: Show script file contents
        run: cat ./src/Build-MarksTemple.ps1
        shell: bash
      - name: Install latest Pester
        run: Install-Module -Name Pester -Force -Scope CurrentUser
        shell: powershell
      - name: Run Pester tests
        run: |
          Import-Module Pester
          Invoke-Pester -Path ./tests -Output Detailed -Verbose
        shell: powershell

  test-windows-pwsh:
    name: PowerShell Core (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repo files
        run: ls -R
        shell: bash
      - name: Show test file contents
        run: cat ./tests/Build-MarksTemple.Tests.ps1
        shell: bash
      - name: Show script file contents
        run: cat ./src/Build-MarksTemple.ps1
        shell: bash
      - name: Install latest Pester
        run: Install-Module -Name Pester -Force -Scope CurrentUser
        shell: pwsh
      - name: Run Pester tests
        run: |
          Import-Module Pester
          Invoke-Pester -Path ./tests -Output Detailed -Verbose
        shell: pwsh

  test-linux-pwsh:
    name: PowerShell Core (Linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repo files
        run: ls -R
        shell: bash
      - name: Show test file contents
        run: cat ./tests/Build-MarksTemple.Tests.ps1
        shell: bash
      - name: Show script file contents
        run: cat ./src/Build-MarksTemple.ps1
        shell: bash
      - name: Install latest Pester
        run: pwsh -c "Install-Module -Name Pester -Force -Scope CurrentUser"
      - name: Run Pester tests
        run: pwsh -c "Import-Module Pester; Invoke-Pester -Path ./tests -Output Detailed -Verbose"

  test-macos-pwsh:
    name: PowerShell Core (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: List repo files
        run: ls -R
        shell: bash
      - name: Show test file contents
        run: cat ./tests/Build-MarksTemple.Tests.ps1
        shell: bash
      - name: Show script file contents
        run: cat ./src/Build-MarksTemple.ps1
        shell: bash
      - name: Install latest Pester
        run: pwsh -c "Install-Module -Name Pester -Force -Scope CurrentUser"
      - name: Run Pester tests
        run: pwsh -c "Import-Module Pester; Invoke-Pester -Path ./tests -Output Detailed -Verbose"