name: Publish Module

on:
    release:
      types: [created]

jobs:
  publish:
    name: Publish to PowerShell Gallery
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PowerShell module cache
        uses: actions/cache@v3
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-ps-modules-${{ hashFiles('**/requirements.psd1') }}

      - name: Install dependencies
        shell: pwsh
        run: |
          Install-Module -Name PowerShellGet -Force -SkipPublisherCheck

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer -Force
          $results = Invoke-ScriptAnalyzer -Path ./src -Recurse
          if ($results) {
            $results | Format-Table
            throw "PSScriptAnalyzer found issues that need to be resolved before publishing."
          }

      - name: Publish module
        shell: pwsh
        env:
          PSGALLERY_API_KEY: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
          $manifestInfo = Test-ModuleManifest -Path ./src/Build-MarksTemple.psd1
          $version = $manifestInfo.Version
          Write-Host "Publishing module version: $version"

          Publish-Module -Path ./src -NuGetApiKey $env:PSGALLERY_API_KEY -Verbose